services:
  server:
    build: ./
    ports:
      - '5000:5000'
    # volumes:
    #     - ./server:/usr/src/app/server
  client:
    build: ./frontend
    # volumes:
    #     - ./client:/usr/src/app/client
    ports:
      - '3000:3000'
