services:
  server:
    build: ./
    ports:
      - '5000:5000'

    container_name: mern-e-commerce_server

    env_file:
      - .env
    # volumes:
    #     - ./server:/usr/src/app/server
  client:
    build: ./frontend
    # volumes:
    #     - ./client:/usr/src/app/client
    ports:
      - '3000:3000'

    container_name: mern-e-commerce_client
  
